#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import time

###SILAH###
os.system("clear")
print("""
			        _ 
                            _-' "'-,     
                         _-' | d$$b |  
                      _-'    | $$$$ |    
                   _-'       | Y$$P |  
                _-'|         |      |
             _-'  _*         |      |
          _-' |_-"      __--''\    /
       _-'         __--'     __*--'
     -'       __-''    __--*__-"`
    |    _--''   __--*"__-'`  
    |_--"  .--=`"__-||"  
    |      |  |\\   ||
    | .dUU |  | \\ //
    | UUUU | _|___//
    | UUUU |  |   
    | UUUU |  |         [Mrpleak termux kurulum]
    | UUUU |  |
    | UUUU |  |
    | UUUU |  |
    | UUP' |  |
    |   ___^-"`
     ""'
""")
time.sleep(2)
print("KURULUM BAŞLIYOR")
time.sleep(2)
os.system("clear")
os.chdir("/data/data/com.termux/files/home")

###BANNER###

banner = """
              a8888b.
             d888888b.
             8P"YP"Y88
             8|o||o|88
             8'    .88
             8`._.' Y8.
            d/      `8b.
          .dP   .     Y8b.
         d8:'   "   `::88b.
        d8"           `Y88b
       :8P     '       :888
        8a.    :      _a88P
      ._/"Yaa_ :    .| 88P|
      \    YP"      `| 8P  `.
      /     \._____.d|    .'
      `--..__)888888P`._.'
(1 - Toolları kur)

(2 - Komutları kur)

(3 - Çıkış)

"""

print(banner)

secim = input("Seçim Yapınız: ")

if secim  == "1":
	os.system("git clone https://github.com/ShuBhamg0sain/Hack_CCTV_Cam-v.3.git")
	os.system("git clone https://github.com/ShuBhamg0sain/trace-ip.git")
	os.system("git clone https://github.com/ShuBhamg0sain/SMSbomber.git")
	os.system("git clone https://github.com/Silent-Blue/Wordlist-Creator.git")
	os.system("git clone https://github.com/ShuBhamg0sain/wifi-passlist.git")
	os.system("git clone https://github.com/ShuBhamg0sain/hack-wifi.git")
	os.system("git clone https://github.com/ShuBhamg0sain/reportbug.git")
	os.system("git clone https://github.com/ShuBhamg0sain/virous.git")
	os.system("git clone https://github.com/ShuBhamg0sain/Locate.git")
	os.system("git clone https://github.com/ShuBhamg0sain/Facebook_hack.git")
	os.system("git clone https://github.com/ShuBhamg0sain/rootkalilinux-termux.git")
	os.system("git clone https://github.com/ShuBhamg0sain/rootubantu-termux.git")
	os.system("git clone https://github.com/ShuBhamg0sain/termux_Arch.git")
	os.system("git clone https://github.com/govolution/avet")
	os.system("git clone https://github.com/ShuBhamg0sain/Facebook-kit.git")
	os.system("git clone https://github.com/ShuBhamg0sain/Fbbrute.git")
	os.system("git clone https://github.com/thewhiteh4t/seeker.git")
	os.system("git clone https://github.com/Findomain/Findomain.git")
	os.system("git clone https://github.com/1aN0rmus/TekDefense-Automater.git")
	os.system("git clone https://github.com/1N3/BruteX.git")
	os.system("git clone https://github.com/1N3/Findsploit.git")
	os.system("git clone https://github.com/1N3/ReverseAPK.git")
	os.system("git clone https://github.com/1N3/Sn1per.git")
	os.system("git clone https://github.com/1tayH/noisy.git")
	os.system("git clone https://github.com/4L13199/LITEDDOS.git")
	os.system("git clone https://github.com/4L13199/LITESPAM.git")
	os.system("git clone https://github.com/4shadoww/hakkuframework.git")
	os.system("git clone https://github.com/4w4k3/BeeLogger.git")
	os.system("git clone https://github.com/4w4k3/KnockMail.git")
	os.system("git clone https://github.com/4w4k3/Umbrella.git")
	os.system("git clone https://github.com/4ZM/mfterm.git")
	os.system("git clone https://github.com/jimywork/djangohunter.git")
	os.system("git clone https://github.com/jimywork/shodanwave.git")
	os.system("git clone https://github.com/a0xnirudh/WebXploiter.git")
	os.system("git clone https://github.com/abaykan/TrackOut.git")
	os.system("git clone https://github.com/abbbe/sslcaudit.git")
	os.system("git clone https://github.com/aboul3la/Sublist3r.git")
	os.system("git clone https://github.com/AeonDave/doork.git")
	os.system("git clone https://github.com/AeonDave/sir.git")
	os.system("git clone https://github.com/anggialberto/xl-py.git")
	os.system("git clone https://github.com/alexxy/netdiscover.git")
	os.system("git clone https://github.com/AlisamTechnology/ATSCAN.git")
	os.system("git clone https://github.com/almandin/fuxploider.git")
	os.system("git clone https://github.com/abaykan/CrawlBox.git")
	os.system("git clone https://github.com/altjx/ipwn.git")
	os.system("git clone https://github.com/andresriancho/w3af.git")
	os.system("git clone https://github.com/AndroBugs/AndroBugs_Framework.git")
	os.system("git clone https://github.com/andyvaikunth/roxysploit.git")
	os.system("git clone https://github.com/AonCyberLabs/PadBuster.git")
	os.system("git clone https://github.com/aquynh/capstone.git")
	os.system("git clone https://github.com/aress31/wirespy.git")
	os.system("git clone https://github.com/arismelachroinos/lscript.git")
	os.system("git clone https://github.com/ASHWIN990/ADB-Toolkit.git")
	os.system("git clone https://github.com/b3-v3r/Hunner.git")
	os.system("git clone https://github.com/BagazMukti/Termux-Styling-Shell-Script.git")
	os.system("git clone https://github.com/bahaabdelwahed/killshot.git")
	os.system("git clone https://github.com/bdblackhat/admin-panel-finder.git")
	os.system("git clone https://github.com/beefproject/beef.git")
	os.system("git clone https://github.com/behindthefirewalls/Parsero.git")
	os.system("git clone https://github.com/bettercap/bettercap.git")
	os.system("git clone https://github.com/bleachbit/bleachbit.git")
	os.system("git clone https://github.com/jofpin/trape.git")
	os.system("git clone https://github.com/byt3bl33d3r/gcat.git")
	os.system("git clone https://github.com/bytezcrew/wfdroid-termux.git")
	os.system("git clone https://github.com/chinoogawa/fbht.git")
	os.system("git clone https://github.com/chrizator/netattack.git")
	os.system("git clone https://github.com/chrizator/netattack2.git")
	os.system("git clone https://github.com/CiKu370/AUXILE.git")
	os.system("git clone https://github.com/CiKu370/hash-generator.git")
	os.system("git clone https://github.com/CiKu370/hasher.git")
	os.system("git clone https://github.com/CiKu370/ko-dork.git")
	os.system("git clone https://github.com/CiKu370/OSIF.git")
	os.system("git clone https://github.com/cinquemb/WifiBruteCrack.git")
	os.system("git clone https://github.com/CISOfy/lynis.git")
	os.system("git clone https://github.com/citronneur/rdpy.git")
	os.system("git clone https://github.com/commixproject/commix.git")
	os.system("git clone https://github.com/cuckoosandbox/cuckoo.git")
	os.system("git clone https://github.com/Cvar1984/Easymap.git")
	os.system("git clone https://github.com/Cvar1984/Ecode.git")
	os.system("git clone https://github.com/Cvar1984/Hac.git")
	os.system("git clone https://github.com/Cvar1984/sqlscan.git")
	os.system("git clone https://github.com/cyberark/shimit.git")
	os.system("git clone https://github.com/cys3c/secHub.git")
	os.system("git clone https://github.com/cyweb/hammer.git")
	os.system("git clone https://github.com/D35m0nd142/Kadabra.git")
	os.system("git clone https://github.com/D35m0nd142/LFISuite.git")
	os.system("git clone https://github.com/D4Vinci/Clickjacking-Tester.git")
	os.system("git clone https://github.com/D4Vinci/Dr0p1t-Framework.git")
	os.system("git clone https://github.com/D4Vinci/elpscrk.git")
	os.system("git clone https://github.com/danielmiessler/SecLists.git")
	os.system("git clone https://github.com/darkoperator/dnsrecon.git")
	os.system("git clone https://github.com/DarkSecDevelopers/HiddenEye-Legacy.git")
	os.system("git clone https://github.com/epsylon/xsser.git")
	os.system("git clone https://github.com/errorBrain/spamchat.git")
	os.system("git clone https://github.com/digininja/CeWL.git")
	os.system("git clone https://github.com/Dionach/CMSmap.git")
	os.system("git clone https://github.com/dotfighter/torshammer.git")
	os.system("git clone https://github.com/EarToEarOak/RTLSDR-Scanner.git")
	os.system("git clone https://github.com/EgeBalci/The-Eye.git")
	os.system("git clone https://github.com/Ekultek/Pybelt.git")
	os.system("git clone https://github.com/EliasOenal/multimon-ng.git")
	os.system("git clone https://github.com/EmpireProject/Empire.git")
	os.system("git clone https://github.com/EnableSecurity/sipvicious.git")
	os.system("git clone https://github.com/EnableSecurity/wafw00f.git")
	os.system("git clone https://github.com/engMaher/BAF.git")
	os.system("git clone https://github.com/epinna/weevely3.git")
	os.system("git clone https://github.com/deadbits/Intersect-2.5.git")
	os.system("git clone https://github.com/derv82/wifite.git")
	os.system("git clone https://github.com/derv82/wifite2.git")
	os.system("git clone https://github.com/esc0rtd3w/wifi-hacker.git")
	os.system("git clone https://github.com/esmog/nodexp.git")
	os.system("git clone https://github.com/evait-security/weeman.git")
	os.system("git clone https://github.com/archival-0x/dedsploit.git")
	os.system("git clone https://github.com/floriankunushevci/rang3r.git")
	os.system("git clone https://github.com/FluxionNetwork/fluxion.git")
	os.system("git clone https://github.com/fnord0/hURL.git")
	os.system("git clone https://github.com/FortyNorthSecurity/EyeWitness.git")
	os.system("git clone https://github.com/fwaeytens/dnsenum.git")
	os.system("git clone https://github.com/g0tmi1k/msfpc.git")
	os.system("git clone https://github.com/galauerscrew/hasherdotid.git")
	os.system("git clone https://github.com/galkan/crowbar.git")
	os.system("git clone https://github.com/Gameye98/AstraNmap.git")
	os.system("git clone https://github.com/Gameye98/Auxscan.git")
	os.system("git clone https://github.com/Gameye98/Black-Hydra.git")
	os.system("git clone https://github.com/Gameye98/FaDe.git")
	os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
	os.system("git clone https://github.com/grafov/hulk.git")
	os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
	os.system("git clone https://github.com/greenbone/openvas-scanner.git")
	os.system("git clone https://github.com/GONZOsint/Namechk.git")
	os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
	os.system("git clone https://github.com/Gameye98/GINF.git")
	os.system("git clone https://github.com/Gameye98/inther.git")
	os.system("git clone https://github.com/Gameye98/Lazymux.git")
	os.system("git clone https://github.com/Gameye98/OWScan.git")
	os.system("git clone https://github.com/Gameye98/santet-online.git")
	os.system("git clone https://github.com/Gameye98/SpazSMS.git")
	os.system("git clone https://github.com/gdabah/distorm.git")
	os.system("git clone https://github.com/GDSSecurity/wifitap.git")
	os.system("git clone https://github.com/geovedi/indonesian-wordlist.git")
	os.system("git clone https://github.com/gitdurandal/dbd.git")
	os.system("git clone https://github.com/GitHackTools/Leaked.git")
	os.system("git clone https://github.com/gkbrk/slowloris.git")
	os.system("git clone https://github.com/golismero/golismero.git")
	os.system("git clone https://github.com/googleinurl/SCANNER-INURLBR.git")
	os.system("git clone https://github.com/grafov/hulk.git")
	os.system("git clone https://github.com/greenbone/openvas.git")
	os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
	os.system("git clone https://github.com/HA71/Namechk.git")
	os.system("git clone https://github.com/hacdias/webdav.git")
	os.system("git clone https://github.com/Hackplayers/4nonimizer.git")
	os.system("git clone https://github.com/the-robot/sqliv.git")
	os.system("git clone https://github.com/hashcat/hashcat.git")
	os.system("git clone https://github.com/hashcat/maskprocessor.git")
	os.system("git clone https://github.com/hatRiot/zarp.git")
	os.system("git clone https://github.com/Hax4us/Metasploit_termux.git")
	os.system("git clone https://github.com/Hax4us/Nethunter-In-Termux.git")
	os.system("git clone https://github.com/Hax4us/TermuxAlpine.git")
	os.system("git clone https://github.com/Hood3dRob1n/BinGoo.git")
	os.system("git clone https://github.com/Hydra7/Planetwork-DDOS.git")
	os.system("git clone https://github.com/i3visio/osrframework.git")
	os.system("git clone https://github.com/ihebski/angryFuzzer.git")
	os.system("git clone https://github.com/ikkebr/PyBozoCrack.git")
	os.system("git clone https://github.com/infobyte/faraday.git")
	os.system("git clone https://github.com/iniqua/plecost.git")
	os.system("git clone https://github.com/nccgroup/keimpx.git")
	os.system("git clone https://github.com/iSECPartners/sslyze.git")
	os.system("git clone https://github.com/JamesJGoodwin/wreckuests.git")
	os.system("git clone https://github.com/jaygreig86/dmitry.git")
	os.system("git clone https://github.com/jesparza/peepdf.git")
	os.system("git clone https://github.com/joswr1ght/cowpatty.git")
	os.system("git clone https://github.com/jothatron/blackbox.git")
	os.system("git clone https://github.com/JPaulMora/Pyrit.git")
	os.system("git clone https://github.com/jseidl/GoldenEye.git")
	os.system("git clone https://github.com/k4m4/kickthemout.git")
	os.system("git clone https://github.com/k4m4/onioff.git")
	os.system("git clone https://github.com/kamorin/DHCPig.git")
	os.system("git clone https://github.com/karulis/pybluez.git")
	os.system("git clone https://github.com/KeepWannabe/Remot3d.git")
	os.system("git clone https://github.com/kgretzky/evilginx2.git")
	os.system("git clone https://github.com/kuburan/txtool.git")
	os.system("git clone https://github.com/LandGrey/pydictor.git")
	os.system("git clone https://github.com/lanmaster53/recon-ng.git")
	os.system("git clone https://github.com/laramies/theHarvester.git")
	os.system("git clone https://github.com/larsbrinkhoff/httptunnel.git")
	os.system("git clone https://github.com/leapsecurity/InSpy.git")
	os.system("git clone https://github.com/lgandx/Responder.git")
	os.system("git clone https://github.com/lightos/credmap.git")
	os.system("git clone https://github.com/linkedin/qark.git")
	os.system("git clone https://github.com/LionSec/wifresti.git")
	os.system("git clone https://github.com/LionSec/xerosploit.git")
	os.system("git clone https://github.com/LOoLzeC/Evil-create-framework.git")
	os.system("git clone https://github.com/LOoLzeC/SH33LL.git")
	os.system("git clone https://github.com/m4ll0k/Infoga.git")
	os.system("git clone https://github.com/m4rktn/zeroeye.git")
	os.system("git clone https://github.com/m8r0wn/subscraper.git")
	os.system("git clone https://github.com/maldevel/IPGeoLocation.git")
	os.system("git clone https://github.com/Manisso/Crips.git")
	os.system("git clone https://github.com/Manisso/Xshell.git")
	os.system("git clone https://github.com/Manisso/fsociety.git")
	os.system("git clone https://github.com/mitmproxy/mitmproxy.git")
	os.system("git clone https://github.com/mnp/xspy.git")
	os.system("git clone https://github.com/Moham3dRiahi/Th3inspector.git")
	os.system("git clone https://github.com/Moham3dRiahi/XAttacker.git")
	os.system("git clone https://github.com/moxie0/sslstrip.git")
	os.system("git clone https://github.com/moyix/creddump.git")
	os.system("git clone https://github.com/Mr-Un1k0d3r/DKMC.git")
	os.system("git clone https://github.com/Hendriyawan/FBUPv2.0.git")
	os.system("git clone https://github.com/MrSqar-Ye/BadMod.git")
	os.system("git clone https://github.com/mschwager/fierce.git")
	os.system("git clone https://github.com/mteg/braa.git")
	os.system("git clone https://github.com/nathanlopez/Stitch.git")
	os.system("git clone https://github.com/nccgroup/demiguise.git")
	os.system("git clone https://github.com/nccgroup/Winpayloads.git")
	os.system("git clone https://github.com/Neo-Oli/termux-ubuntu.git")
	os.system("git clone https://github.com/Neohapsis/bbqsql.git")
	os.system("git clone https://github.com/neoneggplant/EggShell.git")
	os.system("git clone https://github.com/nfc-tools/mfcuk.git")
	os.system("git clone https://github.com/nfc-tools/mfoc.git")
	os.system("git clone https://github.com/nmilosev/termux-fedora.git")
	os.system("git clone https://github.com/NullArray/AutoSploit.git")
	os.system("git clone https://github.com/nxxxu/AutoPixieWps.git")
	os.system("git clone https://github.com/offensive-security/exploitdb.git")
	os.system("git clone https://github.com/OJ/gobuster.git")
	os.system("git clone https://github.com/orgcandman/Simple-Fuzzer.git")
	os.system("git clone https://github.com/OWASP/OWASP-WebScarab.git")
	os.system("git clone https://github.com/OWASP/QRLJacking.git")
	os.system("git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git")
	os.system("git clone https://github.com/p4kl0nc4t/Spammer-Grab.git")
	os.system("git clone https://github.com/pasahitz/zirikatu.git")
	os.system("git clone https://github.com/peterpt/eternal_scanner.git")
	os.system("git clone https://github.com/peterpt/get.git")
	os.system("git clone https://github.com/portcullislabs/enum4linux.git")
	os.system("git clone https://github.com/PowerScript/KatanaFramework.git")
	os.system("git clone https://github.com/PowerShellMafia/PowerSploit.git")
	os.system("git clone https://github.com/qunxyz/proxystrike.git")
	os.system("git clone https://github.com/r00t-3xp10it/FakeImageExploiter.git")
	os.system("git clone https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL.git")
	os.system("git clone https://github.com/r00t-3xp10it/morpheus.git")
	os.system("git clone https://github.com/r00t-3xp10it/trojanizer.git")
	os.system("git clone https://github.com/r00tmars/ExploitOnCLI.git")
	os.system("git clone https://github.com/r00tmars/XPL-SEARCH.git")
	os.system("git clone https://github.com/Rajkumrdusad/MyServer.git")
	os.system("git clone https://github.com/Rajkumrdusad/Tool-X.git")
	os.system("git clone https://github.com/rand0m1ze/ezsploit.git")
	os.system("git clone https://github.com/ReFirmLabs/binwalk.git")
	os.system("git clone https://github.com/threat9/routersploit.git")
	os.system("git clone https://github.com/reyammer/shellnoob.git")
	os.system("git clone https://github.com/rezasp/joomscan.git")
	os.system("git clone https://github.com/Rhi7/shell-scan.git")
	os.system("git clone https://github.com/ring0lab/catphish.git")
	os.system("git clone https://github.com/riverloopsec/killerbee.git")
	os.system("git clone https://github.com/robertdavidgraham/masscan.git")
	os.system("git clone https://github.com/robertswiecki/intrace.git")
	os.system("git clone https://github.com/ron190/jsql-injection.git")
	os.system("git clone https://github.com/royhills/arp-scan.git")
	os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
	os.system("git clone https://github.com/ruped24/killchain.git")
	os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
	os.system("git clone https://github.com/s0md3v/Blazy.git")
	os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
	os.system("git clone https://github.com/s0md3v/sqlmate.git")
	os.system("git clone https://github.com/s0md3v/Striker.git")
	os.system("git clone https://github.com/s0md3v/XSStrike.git")
	os.system("git clone https://github.com/sabri-zaki/EasY_HaCk.git")
	os.system("git clone https://github.com/samratashok/nishang.git")
	os.system("git clone https://github.com/samyk/pwnat.git")
	os.system("git clone https://github.com/sandalpenyok/kojawafft.git")
	os.system("git clone https://github.com/Sanix-Darker/DDosy.git")
	os.system("git clone https://github.com/savio-code/fern-wifi-cracker.git")
	os.system("git clone https://github.com/savio-code/ghost-phisher.git")
	os.system("git clone https://github.com/Screetsec/Brutal.git")
	os.system("git clone https://github.com/Screetsec/Dracnmap.git")
	os.system("git clone https://github.com/Screetsec/LALIN.git")
	os.system("git clone https://github.com/Screetsec/TheFatRat.git")
	os.system("git clone https://github.com/Screetsec/Vegile.git")
	os.system("git clone https://github.com/secretsquirrel/the-backdoor-factory.git")
	os.system("git clone https://github.com/securestate/termineter.git")
	os.system("git clone https://github.com/sensepost/kwetza.git")
	os.system("git clone https://github.com/shawarkhanethicalhacker/D-TECT-1.git")
	os.system("git clone https://github.com/ShawnDEvans/smbmap.git")
	os.system("git clone https://github.com/shekyan/slowhttptest.git")
	os.system("git clone https://github.com/shinnok/johnny.git")
	os.system("git clone https://github.com/SilentGhostX/HT-WPS-Breaker.git")
	os.system("git clone https://github.com/SilverFoxx/PwnSTAR.git")
	os.system("git clone https://github.com/silverhat007/termux-wordpresscan.git")
	os.system("git clone https://github.com/simsong/bulk_extractor.git")
	os.system("git clone https://github.com/siruidops/uidsploit.git")
	os.system("git clone https://github.com/Smaash/fuckshitup.git")
	os.system("git clone https://github.com/Smaash/snitch.git")
	os.system("git clone https://github.com/Souhardya/Zerodoor.git")
	os.system("git clone https://github.com/SpiderLabs/deblaze.git")
	os.system("git clone https://github.com/SpiderLabs/jboss-autopwn.git")
	os.system("git clone https://github.com/sqlmapproject/sqlmap.git")
	os.system("git clone https://github.com/st42/termux-sudo.git")
	os.system("git clone https://github.com/stamparm/DSSS.git")
	os.system("git clone https://github.com/stamparm/DSVW.git")
	os.system("git clone https://github.com/stamparm/DSXS.git")
	os.system("git clone https://github.com/steve-m/kalibrate-rtl.git")
	os.system("git clone https://github.com/StreetSec/Gloom-Framework.git")
	os.system("git clone https://github.com/sullo/nikto.git")
	os.system("git clone https://github.com/SusmithKrishnan/cpscan.git")
	os.system("git clone https://github.com/SusmithKrishnan/torghost.git")
	os.system("git clone https://github.com/swisskyrepo/Wordpresscan.git")
	os.system("git clone https://github.com/t6x/reaver-wps-fork-t6x.git")
	os.system("git clone https://github.com/utkusen/leviathan.git")
	os.system("git clone https://github.com/The404Hacking/websploit.git")
	os.system("git clone https://github.com/thehackingsage/hacktronian.git")
	os.system("git clone https://github.com/ThoughtfulDev/EagleEye.git")
	os.system("git clone https://github.com/tiagorlampert/CHAOS.git")
	os.system("git clone https://github.com/tiagorlampert/sAINT.git")
	os.system("git clone https://github.com/tomac/yersinia.git")
	os.system("git clone https://github.com/trustedsec/ridenum.git")
	os.system("git clone https://github.com/trustedsec/social-engineer-toolkit.git")
	os.system("git clone https://github.com/Tuhinshubhra/CMSeeK.git")
	os.system("git clone https://github.com/Tuhinshubhra/fbvid.git")
	os.system("git clone https://github.com/Tuhinshubhra/RED_HAWK.git")
	os.system("git clone https://github.com/Tuhinshubhra/shellstack.git")
	os.system("git clone https://github.com/Cyb0r9/Androspy.git")
	os.system("git clone https://github.com/Cyb0r9/SocialBox.git")
	os.system("git clone https://github.com/twelvesec/gasmask.git")
	os.system("git clone https://github.com/s0md3v/Breacher.git")
	os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
	os.system("git clone https://github.com/s0md3v/ReconDog.git")
	os.system("git clone https://github.com/s0md3v/sqlmate.git")
	os.system("git clone https://github.com/s0md3v/Striker.git")
	os.system("git clone https://github.com/s0md3v/XSStrike.git")
	os.system("git clone https://github.com/UndeadSec/EvilURL.git")
	os.system("git clone https://github.com/UndeadSec/GoblinWordGenerator.git")
	os.system("git clone https://github.com/UndeadSec/SocialFish.git")
	os.system("git clone https://github.com/urbanadventurer/bing-ip2hosts.git")
	os.system("git clone https://github.com/urbanadventurer/WhatWeb.git")
	os.system("git clone https://github.com/ustayready/CredSniper.git")
	os.system("git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git")
	os.system("git clone https://github.com/vanhauser-thc/thc-ipv6.git")
	os.system("git clone https://github.com/vecna/sniffjoke.git")
	os.system("git clone https://github.com/verluchie/termux-lazysqlmap.git")
	os.system("git clone https://github.com/volatilityfoundation/volatility.git")
	os.system("git clone https://github.com/Wh1t3Rh1n0/air-hammer.git")
	os.system("git clone https://github.com/wifiphisher/wifiphisher.git")
	os.system("git clone https://github.com/wiire-a/pixiewps.git")
	os.system("git clone https://github.com/WiPi-Hunter/PiDense.git")
	os.system("git clone https://github.com/wireghoul/doona.git")
	os.system("git clone https://github.com/wireghoul/dotdotpwn.git")
	os.system("git clone https://github.com/wpscanteam/wpscan.git")
	os.system("git clone https://github.com/x90skysn3k/brutespray.git")
	os.system("git clone https://github.com/xHak9x/fbi.git")
	os.system("git clone https://github.com/xmendez/wfuzz.git")
	os.system("git clone https://github.com/xtr4nge/giskismet.git")
	os.system("git clone https://github.com/Xyl2k/Cookie-stealer.git")
	os.system("git clone https://github.com/Zapotek/cdpsnarf.git")
	os.system("git clone https://github.com/zaproxy/zaproxy.git")
	os.system("git clone https://github.com/zerosum0x0/koadic.git")
	os.system("git clone https://github.com/zigoo0/webpwn3r.git")
	os.system("clear")
elif secim ==  "2":
	os.system("termux-setup-storage")
	os.system("pkg install root-repo unstable-repo x11-repo -y")
	os.system("apt update -y")
	os.system("apt upgrade")
	os.system("pkg install git -y")
	os.system("pkg install python python2 -y")
	os.system("pkg intall python3")
	os.system("pkg install pip")
	os.system("apt install purge-repo -y")
	os.system("pkg install php -y")
	os.system("pkg install perl -y")
	os.system("pkg install nano -y")
	os.system("pkg install vim -y")
	os.system("pkg install cat -y")
	os.system("pkg install pip2 -y")
	os.system("pip install wordlist -y")
	os.system("pkg install nmap -y")
	os.system("pkg install hydra -y")
	os.system("pkg install openssl -y")
	os.system("apt install nodejs -y")
	os.system("clear")
elif secim == "3":
	os.system("clear")
else:
	print("Lütfen Doğru Seçim Yapınız!!!")
